### ISSUE TITLE
Poor gardening at The Parks

### ISSUE THREAD

**Issue by Thurgarton66** [theparksilford/Issues#26] opened 2022-05-09 15:19 UTC
### Property Details

22 Blackthorn Road

### Contact Details

Rgthrow@gmail.com

### Type of problem?

Ground Maintenance

### Since when this issue started?

5 May 2022

### Issue Description?

No hedges/shrubs have been trimmed. No weeding done of flower beds

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment] 2022-05-11 12:16
Closing this issue as this is a duplicate of other issue where photos have been posted.

**Closed by theparksilford** 2022-05-11 12:16 UTC
