### ISSUE TITLE
CCTV Activation and Signs

### ISSUE THREAD

**Issue by theparksilford** [theparksilford/Issues#11] opened 2021-11-16 18:49 UTC
### Property Details

General Estate

### Type of problem?

General Issue

### Since when this issue started?

July 2021

### Issue Description?

We have commissioned the CCTV for sometime now but for several reasons its not activated still, please let us know when it will be activated and when the signs will be posted.

### Logged By

Leaseholder or FreeHolder

**Comment by theparksilford** [comment] 2021-11-18 14:45
Had a chat with CCTV guys, asked them to include 2-3 more cameras to have better coverage. They informed me that BT got the line but it needs to be activated. RR should get this sorted so that the CCTV is activated. This is becoming urgent now.

**Comment by jeremydoran** [comment] 2021-11-19 16:35
I spoke with SMS the CCTV contractor today and I have been advised that he attended yesterday however he was unable to connected the CCTV as the broadband line had not been activated in which BT advised that it was, I will contact BT and ask that they re-attend. 

SMS will also be sending over the quotes for the additional cameras in the next couple of days.

The CCTV signs will be erected at the same time as when the cameras get activated.

**Comment by jeremydoran** [comment] 2021-11-27 17:53
BT have been contacted and we are awaiting another appointment for an engineer to come and advise why we still don’t have a working broadband line as advised by the company that has installed the CCTV.

Once a date has been arranged with BT we will ask the CCTV company to attend at the same time to finish the commissioning of the system and install the relevant CCTV signs along with any additional cameras if approved. 

I have asked SMS (The CCTV Company) to send me a formal quote on email. 

I am aware that we need to get this CCTV up and running as soon as we can and I hope to have an update from BT in the coming days.

**Comment by jeremydoran** [comment] 2021-12-02 18:15
BT have been contacted several times this week regarding the broadband line issue that still remains outstanding. 

BT have now confirmed its an external issue and we won’t need to provide access, the appointment is booked for Monday morning (06.12.21). 

The CCTV company are aware and will confirm what day next week they are able to attend to commission the system as required and to install the relevant CCTV signs and any additional cameras.

**Comment by jeremydoran** [comment] 2021-12-03 19:07
The CCTV company have now confirmed that they plan to attend next Tuesday (07.12.21) to install another additional 4 cameras, install the relevant CCTV signage to comply with GDPR and to commission the system.

**Comment by jeremydoran** [comment] 2021-12-06 17:03
I have spoken with the CCTV company today who have confirmed they still plan to attend tomorrow (07.12.21) to install the additional 4 cameras, install the relevant CCTV signage and to commission the system.

**Comment by jeremydoran** [comment] 2021-12-07 17:45
The contractor has advised that he was unable to attend today as planned due to the rain, he required a dry day to install the additional cameras. 

The CCTV contractor plans to re-attend sometime this week.

Once I have a further update I will let you know.

**Comment by theparksilford** [comment] 2021-12-07 17:46
Thanks, have we got the line working and BT did their job?

**Comment by jeremydoran** [comment] 2021-12-07 18:04
BT haven’t called me to confirmed as promised so I’m not aware.

I will call BT tomorrow to confirm.

Kind regards,

Jeremy  Doran
Senior Property Manager

Red Rock Estate & Property Management LTD |
0333 123 5670 '| www.rrpm.co.uk<http://www.rrpm.co.uk/> : | 07788 372820 '
@Red_RockPM  [Logo  Description automatically generated] <https://www.facebook.com/Red-Rock-Estate-Property-Management-134879723861470>  [Logo  Description automatically generated] <https://twitter.com/Red_RockPM>  | Red Rock Estate & Property Management  [Logo  Description automatically generated] <https://www.linkedin.com/company/74057114/admin/>  |

[Logo  Description automatically generated]<https://www.rrpm.co.uk/>[Logo  Description automatically generated]

Red Rock Estate & Property Management Ltd, Red Rock House, Oak Business Park, Wix Road, Beaumont CO16 0AT
Red Rock PBS Ltd, 40 Church Road, Stanmore, Middlesex HA7 4AH

Disclaimer
This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Red Rock Estate & Property Management Ltd. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please notify Red Rock Estate & Property Management Ltd ***@***.******@***.***> |Where the subject of this communication is in respect of a site where a separate Management Company was incorporated, Red Rock Estate & Property Management Ltd are communicating on behalf of that Management Company.
Registered Address: Red Rock Estate & Property Management Ltd Suite 19 North Colchester Business Centre, 340 The Crescent, Colchester, Essex, CO4 9AD | Company Registration Number 06978934 | VAT No. 976294174
Red Rock Estate & Property Management Ltd is in full support of the ‘Unreasonable Behaviour Policy’<https://irpm.org.uk/media/imcgxhro/arma-and-irpm-unreasonable-behaviour-policy.docx> published by ARMA and IRPM to abolish abuse within the Property Management Sector and is dedicated in taking steps to safeguard the wellbeing of its employees.
In the unlikely event that you have not received a response within 5 working days, please forward your original email to our Administration Manager at ***@***.******@***.***> with the title “ESCALATE” and it will be tracked as a Quality issue.
Your opinion is important to us. If you feel we've provided great service or would like to leave us feedback, please rate us on Google<https://search.google.com/local/writereview?placeid=ChIJBw_A2dVy2UcRey4IJhmYWuw>.

Please consider the environment before printing this e-mail. P

[signature_472255410][signature_1128482106][Icon  Description automatically generated]

Disclaimer
This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of Red Rock Estate & Property Management Ltd. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please notify Red Rock Estate &Property Management Ltd ***@***.******@***.***> |Where the subject of this communication is in respect of a site where a separate Management Company was incorporated, Red Rock Estate & Property Management Ltd are communicating on behalf of that Management Company.
Registered Address: Red Rock Estate & Property Management Ltd Suite 19 North Colchester Business Centre, 340 The Crescent, Colchester, Essex, England, CO4 9AD| Company Registration Number 06978934 | VAT No. 976294174
Please consider the environment before printing this e-mail. P
***@***.***[http://images.leaseholdknowledge.com/wp-content/uploads/2012/06/LKPmastheadlogo.gif] ***@***.***

**Comment by jeremydoran** [comment] 2021-12-08 16:34
BT have been contacted today to confirm if the issue with the broadband line has been rectified however BT were unable to provide me with any update on this issue and I have been advised I will received a call tomorrow with a full update.  

I will update everyone on this shortly. 

Fault ref: 1-108762187 / Contact number: 0800 800154

**Comment by jeremydoran** [comment] 2021-12-09 18:32
BT have been called again today as I wasn't called back with any update as promised. 
I have now been told I will be getting a call tomorrow or Monday to inform me if the outstanding issue with the broadband line  has been resolved. 

I will update everyone again as soon as I can on this matter.

**Comment by jeremydoran** [comment] 2021-12-13 17:55
I have now manage to arrange for BT & the CCTV company to attend this Thursday 16th December in the morning.

**Comment by theparksilford** [comment] 2021-12-16 21:30
What’s the status now?

**Comment by jeremydoran** [comment] 2021-12-17 11:33
The Fault with BT has now been resolved this week. 

The new additional 4 cameras will be installed next week to complete this installation.

**Comment by theparksilford** [comment] 2021-12-22 13:04
As per the CCTV installers “ All cameras are active but internet is not great”. 
What we do here? Please provide the date when we will have access to it.

**Comment by jeremydoran** [comment] 2021-12-22 13:52
The CCTV contractor is going attending tomorrow morning to investigate and to reset the internet router.

I have also asked the contractor to provide an update as to when the training for the CCTV will be given.

**Comment by jeremydoran** [comment] 2021-12-29 17:52
This job is now complete with all the cameras working correctly and the broadband line working as it should be. 

The CCTV company is now in the process of arranging for suitable training for those who are authorised to use and view the CCTV footage.

**Comment by jeremydoran** [comment] 2022-01-28 14:18
The contractor has attended site today to finish off the CCTV works and to install the remaining signs around the development.

**Comment by jeremydoran** [comment] 2022-02-04 15:01
The CCTV signs have been installed by the contractor.

**Comment by jeremydoran** [comment] 2022-02-10 16:23
The CCTV letter has been sent out today advising all residents.

**Comment by jeremydoran** [comment] 2022-05-17 18:16
The CCTV signs have now been put up on every bin shed door and some walls.

**Closed by jeremydoran** 2022-05-17 18:16 UTC
